spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:9196}
server:
  port: ${GATEWAY_PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
jwt:
  secret: ${JWT_SECRET:MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}