spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
      routes:
        - id: COMMERCE-SERVICE
          uri: lb://commerce-service
          predicates:
            - Path=/commerce/**
        - id: MANAGEMENT-SERVICE
          uri: lb://management-service
          predicates:
            - Path=/management/**
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: PAYMENT-SERVICE
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:9196}
server:
  port: ${GATEWAY_PORT:8099}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /commerce/v3/api-docs
        name: Ventas Service
    urls-primary-name: API Gateway Service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOSTNAME:localhost}